package awtzero;


import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.HashSet;
import java.util.Set;

/**
 * Keyboard class to handle keyboard input.
 * It is recommended to use the enums in Key.java for key codes.
 * @see Key
 */
public class Keyboard implements KeyListener {
    private final Set<Integer> keysDown = new HashSet<>();

    /**
     * Function to get key press events. <strong>Do not call this directly.</strong>
     * @param e KeyEvent generated by AWT
     */
    @Override
    public void keyPressed(KeyEvent e) {
        keysDown.add(e.getKeyCode());
    }

    /**
     * Function to get key release events. <strong>Do not call this directly.</strong>
     * @param e KeyEvent generated by AWT
     */
    @Override
    public void keyReleased(KeyEvent e) {
        keysDown.remove(e.getKeyCode());
    }

    /**
     * Function to <strong>ignore</strong> key press events. <strong>Do not call this directly.</strong>
     * @param e KeyEvent generated by AWT
     */
    @Override
    public void keyTyped(KeyEvent e) {}

    /**
     * Check if a specific key is currently pressed down.
     * @param key Key enum representing the key to check
     * @return {@code true} if the key is pressed down, {@code false} otherwise
     * @see Key
     */
    public boolean isKeyDown(Key key) {
        return keysDown.contains(key.code);
    }
} 

